version: '3'
networks:
  web:
    external: true
  codemooc-reg-backend:

services:
  web:
    build: ../src/Web
    depends_on:
    - db
    networks:
    - web
    - codemooc-reg-backend
    env_file:
    - config.env
    - secret.env
    expose:
    - 5001
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=5001"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
    - "traefik.frontend.priority=100"

  db:
    image: mysql:5.7
    networks:
    - codemooc-reg-backend
    env_file: config.env

  db-client:
    build: ../src/MysqlClient
    depends_on:
    - db
    networks:
    - codemooc-reg-backend
    env_file: config.env

  donation-manager:
    build: ../src/DonationManager
    depends_on:
    - db
    networks:
    - codemooc-reg-backend
    env_file:
    - config.env
    - secret.env
