version: '3'
volumes:
  codemooc-reg-db:
    external: true

services:
  web:
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    labels:
    - "traefik.frontend.rule=Host:codemooc.net;PathPrefix:/iscrizione,/statuto,/static,/badge"
    restart: unless-stopped

  db:
    volumes:
    - codemooc-reg-db:/var/lib/mysql:rw
    restart: unless-stopped

  timer:
    build: ../src/Timer
    networks:
    - codemooc-reg-backend
    volumes:
    - ../:/code/:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw
    env_file:
    - config.env
    - secret.env
    restart: unless-stopped
