version: '3'
volumes:
  codemooc-reg-db:
    external: true

services:
  web:
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    labels:
    - "traefik.frontend.rule=Host:codemooc.net;PathPrefix:/iscrizione,/statuto,/static,/badge"

  db:
    volumes:
    - codemooc-reg-db:/var/lib/mysql:rw

  timer:
    image: lorenzck/crontaimer:1.0
    networks:
    - codemooc-reg-backend
    volumes:
    - ../:/code/:ro
    - ../src/Timer/cronjobs:/etc/crontabs/root:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw
    env_file:
    - config.env
    - secret.env
