//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMooc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BadgeEvidenceDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BadgeEvidenceDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeMooc.Web.Resources.BadgeEvidenceDescriptions", typeof(BadgeEvidenceDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;SOSTENITORE&amp;nbsp;GOLD&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 100&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2019 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string GoldPatron2019 {
            get {
                return ResourceManager.GetString("GoldPatron2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;SOSTENITORE&amp;nbsp;GOLD&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 100&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net-2020/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2020 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string GoldPatron2020 {
            get {
                return ResourceManager.GetString("GoldPatron2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;SOSTENITORE&amp;nbsp;GOLD&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 100&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net-2021/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2021 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string GoldPatron2021 {
            get {
                return ResourceManager.GetString("GoldPatron2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è &lt;b&gt;SOCIO/A&lt;/b&gt; dell’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET”, in regola con il versamento della quota associativa per il&amp;nbsp;2019.&lt;/p&gt;.
        /// </summary>
        public static string Member2019 {
            get {
                return ResourceManager.GetString("Member2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è &lt;b&gt;SOCIO/A&lt;/b&gt; dell’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET”, in regola con il versamento della quota associativa per il&amp;nbsp;2020.&lt;/p&gt;.
        /// </summary>
        public static string Member2020 {
            get {
                return ResourceManager.GetString("Member2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è &lt;b&gt;SOCIO/A&lt;/b&gt; dell’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET”, in regola con il versamento della quota associativa per il&amp;nbsp;2021.&lt;/p&gt;.
        /// </summary>
        public static string Member2021 {
            get {
                return ResourceManager.GetString("Member2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;SOSTENITORE&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 50&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2019 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string Patron2019 {
            get {
                return ResourceManager.GetString("Patron2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;SOSTENITORE&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 50&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net-2020/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2020 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string Patron2020 {
            get {
                return ResourceManager.GetString("Patron2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;SOSTENITORE&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 50&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net-2021/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2021 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string Patron2021 {
            get {
                return ResourceManager.GetString("Patron2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;DONATORE&amp;nbsp;SPONSOR&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 1000&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2019 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string Sponsor2019 {
            get {
                return ResourceManager.GetString("Sponsor2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;DONATORE&amp;nbsp;SPONSOR&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 1000&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net-2020/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2020 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string Sponsor2020 {
            get {
                return ResourceManager.GetString("Sponsor2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Si certifica che {0} {1} ({2}) è un &lt;b&gt;DONATORE&amp;nbsp;SPONSOR&lt;/b&gt; di CODEMOOC&amp;nbsp;NET, avendo partecipato con un contribuito non inferiore a 1000&amp;nbsp;Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net-2021/&quot;&gt;campagna di crowdfuding&lt;/a&gt; lanciata per il 2021 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC&amp;nbsp;NET” per azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string Sponsor2021 {
            get {
                return ResourceManager.GetString("Sponsor2021", resourceCulture);
            }
        }
    }
}
