//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMooc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BadgeDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BadgeDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeMooc.Web.Resources.BadgeDescriptions", typeof(BadgeDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Questo open badge viene rilasciato a chiunque si configuri come &lt;b&gt;SOSTENITORE GOLD&lt;/b&gt;, avendo partecipato con un contribuito non inferiore a 100 Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net/&quot;&gt;campagna di crowdfunding&lt;/a&gt; lanciata per il 2019 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC NET” a favore di azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string GoldPatron2019 {
            get {
                return ResourceManager.GetString("GoldPatron2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Questo open badge viene rilasciato ai soci effettivi dell’Associazione di Promozione Sociale e Culturale “CODEMOOC NET” in regola con il versamento della quota associativa per il 2019.&lt;/p&gt;.
        /// </summary>
        public static string Member2019 {
            get {
                return ResourceManager.GetString("Member2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Questo open badge viene rilasciato a chiunque si configuri come &lt;b&gt;SOSTENITORE&lt;/b&gt;, avendo partecipato con un contribuito non inferiore a 50 Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net/&quot;&gt;campagna di crowdfunding&lt;/a&gt; lanciata per il 2019 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC NET” a favore di azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string Patron2019 {
            get {
                return ResourceManager.GetString("Patron2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Questo open badge viene rilasciato a chiunque si configuri come &lt;b&gt;DONATORE SPONSOR&lt;/b&gt;, avendo partecipato con un contribuito non inferiore a 1000 Euro alla &lt;a href=&quot;https://www.produzionidalbasso.com/project/codemooc-net/&quot;&gt;campagna di crowdfunding&lt;/a&gt; lanciata per il 2019 dall’Associazione di Promozione Sociale e Culturale “CODEMOOC NET” a favore di azioni di promozione del pensiero computazionale e del coding a scuola.&lt;/p&gt;.
        /// </summary>
        public static string Sponsor2019 {
            get {
                return ResourceManager.GetString("Sponsor2019", resourceCulture);
            }
        }
    }
}
