//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMooc.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BadgeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BadgeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeMooc.Web.Resources.BadgeNames", typeof(BadgeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostenitore Gold.
        /// </summary>
        public static string GoldPatron2019 {
            get {
                return ResourceManager.GetString("GoldPatron2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostenitore Gold.
        /// </summary>
        public static string GoldPatron2020 {
            get {
                return ResourceManager.GetString("GoldPatron2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostenitore Gold.
        /// </summary>
        public static string GoldPatron2021 {
            get {
                return ResourceManager.GetString("GoldPatron2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socio 2019.
        /// </summary>
        public static string Member2019 {
            get {
                return ResourceManager.GetString("Member2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socio 2020.
        /// </summary>
        public static string Member2020 {
            get {
                return ResourceManager.GetString("Member2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socio 2021.
        /// </summary>
        public static string Member2021 {
            get {
                return ResourceManager.GetString("Member2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostenitore.
        /// </summary>
        public static string Patron2019 {
            get {
                return ResourceManager.GetString("Patron2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostenitore.
        /// </summary>
        public static string Patron2020 {
            get {
                return ResourceManager.GetString("Patron2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostenitore.
        /// </summary>
        public static string Patron2021 {
            get {
                return ResourceManager.GetString("Patron2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donatore Sponsor.
        /// </summary>
        public static string Sponsor2019 {
            get {
                return ResourceManager.GetString("Sponsor2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donatore Sponsor.
        /// </summary>
        public static string Sponsor2020 {
            get {
                return ResourceManager.GetString("Sponsor2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donatore Sponsor.
        /// </summary>
        public static string Sponsor2021 {
            get {
                return ResourceManager.GetString("Sponsor2021", resourceCulture);
            }
        }
    }
}
